=== Docker Build Log for 6c168b0c36ca3b23cacc ===
Started at: Mi 29. Okt 16:49:13 CET 2025

[2025-10-29 16:49:13] START: Building image for 6c168b0c36ca3b23cacc
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 367B done
#1 DONE 0.0s

#2 [internal] load metadata for docker.io/library/python:3.11
#2 DONE 0.0s

#3 [internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.0s

#4 [internal] load build context
#4 transferring context: 2.91kB 0.0s done
#4 DONE 0.0s

#5 [1/9] FROM docker.io/library/python:3.11
#5 CACHED

#6 [2/9] COPY hard-gists/6c168b0c36ca3b23cacc/snippet.py /snippet.py
#6 DONE 0.1s

#7 [3/9] RUN ["pip","install","zipnish"]
#7 2.015 Collecting zipnish
#7 2.050   Downloading zipnish-0.1.5.tar.gz (1.6 MB)
#7 2.138      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 18.9 MB/s eta 0:00:00
#7 2.252   Preparing metadata (setup.py): started
#7 2.661   Preparing metadata (setup.py): finished with status 'done'
#7 2.687 Collecting simplemysql (from zipnish)
#7 2.697   Downloading simplemysql-1.25.tar.gz (4.5 kB)
#7 2.709   Preparing metadata (setup.py): started
#7 2.829   Preparing metadata (setup.py): finished with status 'done'
#7 2.864 Collecting flask (from zipnish)
#7 2.873   Downloading flask-3.1.2-py3-none-any.whl.metadata (3.2 kB)
#7 3.214 Collecting sqlalchemy (from zipnish)
#7 3.226   Downloading sqlalchemy-2.0.44-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.5 kB)
#7 3.281 Collecting flask_sqlalchemy (from zipnish)
#7 3.291   Downloading flask_sqlalchemy-3.1.1-py3-none-any.whl.metadata (3.4 kB)
#7 3.330 Collecting blinker>=1.9.0 (from flask->zipnish)
#7 3.338   Downloading blinker-1.9.0-py3-none-any.whl.metadata (1.6 kB)
#7 3.386 Collecting click>=8.1.3 (from flask->zipnish)
#7 3.393   Downloading click-8.3.0-py3-none-any.whl.metadata (2.6 kB)
#7 3.427 Collecting itsdangerous>=2.2.0 (from flask->zipnish)
#7 3.435   Downloading itsdangerous-2.2.0-py3-none-any.whl.metadata (1.9 kB)
#7 3.474 Collecting jinja2>=3.1.2 (from flask->zipnish)
#7 3.482   Downloading jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
#7 3.576 Collecting markupsafe>=2.1.1 (from flask->zipnish)
#7 3.585   Downloading markupsafe-3.0.3-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (2.7 kB)
#7 3.638 Collecting werkzeug>=3.1.0 (from flask->zipnish)
#7 3.646   Downloading werkzeug-3.1.3-py3-none-any.whl.metadata (3.7 kB)
#7 3.836 Collecting greenlet>=1 (from sqlalchemy->zipnish)
#7 3.848   Downloading greenlet-3.2.4-cp311-cp311-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (4.1 kB)
#7 3.902 Collecting typing-extensions>=4.6.0 (from sqlalchemy->zipnish)
#7 3.910   Downloading typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
#7 4.045 Collecting mysql-python (from simplemysql->zipnish)
#7 4.057   Downloading MySQL-python-1.2.5.zip (108 kB)
#7 4.071      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 108.9/108.9 kB 8.3 MB/s eta 0:00:00
#7 4.079   Preparing metadata (setup.py): started
#7 4.171   Preparing metadata (setup.py): finished with status 'error'
#7 4.174   error: subprocess-exited-with-error
#7 4.174   
#7 4.174   × python setup.py egg_info did not run successfully.
#7 4.174   │ exit code: 1
#7 4.174   ╰─> [8 lines of output]
#7 4.174       Traceback (most recent call last):
#7 4.174         File "<string>", line 2, in <module>
#7 4.174         File "<pip-setuptools-caller>", line 34, in <module>
#7 4.174         File "/tmp/pip-install-570csogg/mysql-python_e06f3721d7744a03a611ba13fc2c63ae/setup.py", line 13, in <module>
#7 4.174           from setup_posix import get_config
#7 4.174         File "/tmp/pip-install-570csogg/mysql-python_e06f3721d7744a03a611ba13fc2c63ae/setup_posix.py", line 2, in <module>
#7 4.174           from ConfigParser import SafeConfigParser
#7 4.174       ModuleNotFoundError: No module named 'ConfigParser'
#7 4.174       [end of output]
#7 4.174   
#7 4.174   note: This error originates from a subprocess, and is likely not a problem with pip.
#7 4.175 error: metadata-generation-failed
#7 4.175 
#7 4.175 × Encountered error while generating package metadata.
#7 4.175 ╰─> See above for output.
#7 4.175 
#7 4.175 note: This is an issue with the package mentioned above, not pip.
#7 4.175 hint: See above for details.
#7 4.269 
#7 4.269 [notice] A new release of pip is available: 24.0 -> 25.3
#7 4.269 [notice] To update, run: pip install --upgrade pip
#7 ERROR: process "pip install zipnish" did not complete successfully: exit code: 1
------
 > [3/9] RUN ["pip","install","zipnish"]:
4.175 error: metadata-generation-failed
4.175 
4.175 × Encountered error while generating package metadata.
4.175 ╰─> See above for output.
4.175 
4.175 note: This is an issue with the package mentioned above, not pip.
4.175 hint: See above for details.
4.269 
4.269 [notice] A new release of pip is available: 24.0 -> 25.3
4.269 [notice] To update, run: pip install --upgrade pip
------
Dockerfile:3
--------------------
   1 |     FROM python:3.11
   2 |     COPY hard-gists/6c168b0c36ca3b23cacc/snippet.py /snippet.py
   3 | >>> RUN ["pip","install","zipnish"]
   4 |     RUN ["pip","install","numpy"]
   5 |     RUN ["pip","install","scipy"]
--------------------
ERROR: failed to build: failed to solve: process "pip install zipnish" did not complete successfully: exit code: 1

View build details: docker-desktop://dashboard/build/default/default/o78xtpwp05pl74p467pk8crmw
[2025-10-29 16:49:18] ERROR: Build failed for 6c168b0c36ca3b23cacc
